<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Category' => 'Categoría',
    'Supplier' => 'Proveedor',
    'Academic Year' => 'Año académico',
    'Add item' => 'Añadir artículo',
    'Address' => 'Dirección',
    'Amount' => 'Importe',
    'Are you sure you want to delete this item?' => '¿Está seguro de que quiere eliminar este artículo?',
    'Are you sure you want to order to this supplier?' => '¿Está seguro de que quiere eliminar el pedido a este proveedor?',
    'Are you sure you want to receipt this units?' => '¿Está seguro de que quiere recepcionar estas unidades?',
    'Brand' => 'Marca',
    'Cannot delete this item.' => 'No se puede borrar el artículo',
    'Cif' => 'CIF',
    'Class ID' => 'ID clase',
    'Classes' => 'Clases',
    'Comment' => 'Comentario',
    'Contact Name' => 'Nombre de contacto',
    'Contact Phone' => 'Teléfono de contacto',
    'Create' => 'Crear',
    'Create Classes' => 'Crear clases',
    'Create Degrees' => 'Crear cursos',
    'Create Item Categories' => 'Crear categorías de artículo',
    'Create Items' => 'Crear artículos',
    'Create Line Details' => 'Crear detalle de línea',
    'Create Orders' => 'Crear pedidos',
    'Create Stocks' => 'Crear stocks',
    'Create Sub Order Lines' => 'Crear líneas de sub pedido',
    'Create Sub Orders' => 'Crear sub pedidos',
    'Create Subjects' => 'Crear asignaturas',
    'Create Suppliers' => 'Crear proveedores',
    'Create Teachers' => 'Crear profesores',
    'Degree ID' => 'ID curso',
    'Degrees' => 'Cursos',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Discount' => 'Descuento',
    'Email' => 'Correo electrónico',
    'Final Price' => 'Precio final',
    'Id Suborder' => 'ID sub pedido',
    'Item Categories' => 'Categorías de artículo',
    'Item Category ID' => 'ID categoría de artículo',
    'Item ID' => 'ID artículo',
    'Items' => 'Artículos',
    'Legal Name' => 'Razón social',
    'Line Detail ID' => 'ID detalle de línea',
    'Line Details' => 'Detalles de línea',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar sesión',
    'Materials Management' => 'Gestión de materiales',
    'Model' => 'Modelo',
    'Name' => 'Nombre',
    'Order' => 'Pedido',
    'Order ID' => 'ID pedido',
    'Orders' => 'Pedidos',
    'Phone Number' => 'Número teléfono',
    'Price' => 'Precio',
    'Receipt' => 'Entrega',
    'Receipt Unit' => 'Unidad de entrega',
    'Reset' => 'Volver',
    'Search' => 'Buscar',
    'Stock ID' => 'ID stock',
    'Stocks' => 'Stocks',
    'Sub Order Lines' => 'Líneas de sub pedido',
    'Sub Orders' => 'Sub pedidos',
    'Subject ID' => 'ID asignatura',
    'Subjects' => 'Asignaturas',
    'Suborder Line ID' => 'ID línea sub pedido',
    'Supplier ID' => 'ID proveedor',
    'Supplier Reference' => 'Referencia proveedor',
    'Suppliers' => 'Proveedores',
    'Teacher ID' => 'ID profesor',
    'Teachers' => 'Profesores',
    'Unit' => 'Unidad',
    'Unit Price' => 'Precio unitario',
    'Units' => 'Unidades',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}:',
    'Value Date' => 'Fecha valor',
    'Www' => 'www',
];
